"nnoremap <leader>h :WintabsPrevious<CR>
"nnoremap <leader>l :WintabsNext<CR>
map <leader>h <Plug>(wintabs_previous)
map <leader>l <Plug>(wintabs_next)
map <leader>d <Plug>(wintabs_close)
map <leader>dd <Plug>(wintabs_undo)
"map <C-T>o <Plug>(wintabs_only)
"map <C-W>c <Plug>(wintabs_close_window)
"map <C-W>o <Plug>(wintabs_only_window)
